---
- name: Install php5-cli
  apt: name=php5-cli state=latest

- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = America/New_York'

- name: Install php5
  apt: name=php5 state=latest

- name: Ensure timezone is set in apache php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = America/New_York'

- name: Install mcrypt
  apt: name=php5-mcrypt state=present

- name: Enable mcrypt
  shell: sudo php5enmod mcrypt
  notify:
    - reload apache