# -*- mode: ruby -*-
# vi: set ft=ruby :

# Config Github Settings
github_username = "fideloper"
github_repo     = "Vaprobash"
github_branch   = "1.4.0"
github_url      = "https://raw.githubusercontent.com/#{github_username}/#{github_repo}/#{github_branch}"

# Because this:https://developer.github.com/changes/2014-12-08-removing-authorizations-token/
# https://github.com/settings/tokens
github_pat          = ""

# Server Configuration

# hostname        = "ansible-worker.dev"

# Set a local private network IP address.
# See http://en.wikipedia.org/wiki/Private_network for explanation
# You can use the following IP ranges:
#   10.0.0.1    - 10.255.255.254
#   172.16.0.1  - 172.31.255.254
#   192.168.0.1 - 192.168.255.254
# server_ip             = "192.168.22.16"
server_cpus           = "1"   # Cores
server_memory         = "512" # MB
server_swap           = "768" # Options: false | int (MB) - Guideline: Between one or two times the server_memory

# UTC        for Universal Coordinated Time
# EST        for Eastern Standard Time
# US/Central for American Central
# US/Eastern for American Eastern
server_timezone  = "UTC"


Vagrant.configure("2") do |config|

  # Set server to Ubuntu 14.04
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :haproxy do |haproxy|
    haproxy.vm.network :private_network, ip:"192.168.1.16"
    haproxy.vm.network :forwarded_port, guest: 80, host: 8000
    haproxy.vm.hostname = "haproxy.dev"
    config.vm.provider :virtualbox do |vb|
      vb.name = "Ansible-Worker-HAProxy"
      vb.customize ["modifyvm", :id, "--cpus", server_cpus]
      vb.customize ["modifyvm", :id, "--memory", server_memory]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end
  end

  config.vm.define :appserver1 do |app|
    app.vm.network :private_network, ip:"192.168.1.17"
    app.vm.network :forwarded_port, guest: 8000, host: 8001
    app.vm.hostname = "app1"
    config.vm.provider :virtualbox do |vb|
      vb.name = "Ansible-Worker-App1"
      vb.customize ["modifyvm", :id, "--cpus", server_cpus]
      vb.customize ["modifyvm", :id, "--memory", server_memory]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end
  end

  config.vm.define :appserver2 do |app|
    app.vm.network :private_network, ip:"192.168.1.18"
    app.vm.network :forwarded_port, guest: 8000, host: 8002
    app.vm.hostname = "app2"
    config.vm.provider :virtualbox do |vb|
      vb.name = "Ansible-Worker-App2"
      vb.customize ["modifyvm", :id, "--cpus", server_cpus]
      vb.customize ["modifyvm", :id, "--memory", server_memory]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end
  end

  config.vm.define :db do |db|
    db.vm.network :private_network, ip:"192.168.1.19"
    db.vm.network :forwarded_port, guest: 3306, host: 33060
    db.vm.hostname = "db1"
    config.vm.provider :virtualbox do |vb|
      vb.name = "Ansible-Worker-DB"
      vb.customize ["modifyvm", :id, "--cpus", server_cpus]
      vb.customize ["modifyvm", :id, "--memory", server_memory]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end
  end

  ####
  # Base Items
  ##########

  # Provision Base Packages
  config.vm.provision "shell", path: "#{github_url}/scripts/base.sh", args: [github_url, server_swap, server_timezone]

  # optimize base box
  config.vm.provision "shell", path: "#{github_url}/scripts/base_box_optimizations.sh", privileged: true

end
